### ISSUE TITLE
Example Invoke get_sensors_data

### ISSUE THREAD

**Issue by convolutionbbs** [csm10495/purpleair#1]
Thanks for making this!  Not really an issue, but a request.

Could you put an example or two in the readme as to how to invoke the get_sensors_data function?  Looking to have multiple paramaters such as location_type=0 (outdoor) and a modified_since = x.

Thanks!

**Comment by csm10495** [comment]
Sure thing. I was making an example, but may have found an issue with the modified_since part of the API. I've emailed Purple Air for clarification. Once that's settled, I'll add an example.

**Comment by csm10495** [comment]
Turns out the issue was on my end. Updated a few things and added an example to the readme in a5a993b

Thanks!

**Comment by convolutionbbs** [comment]
Thanks for updating this - seems to work great!
